# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
warnings_are_errors: false

r_github_packages:
  - r-lib/covr

after_success:
  - Rscript -e 'covr::coveralls()'
  - Rscript -e 'lintr::lint_package()'
  - Rscript -e 'covr::codecov(token = "20f4d82b-695a-48d5-92ef-1f492b2e8ecc")'
