
#' help remembering
#'
#' @return a cheat list
#' @export
meltdown <- function() {
  melt <- list(
    "NMR" = list(method = c("noesy",
                            "cpmg",
                            "jres",
                            "dire",
                            "diff"),
                 sampleType = c("sample",
                                "pqc",
                                "standard",
                                "ltr")),
    "MRMS" = list(method = c("DIPI",
                             "DINI"),
                 sampleType = c("sample",
                                "blank",
                                "qc",
                                "pqc",
                                "standard",
                                "ltr")),
    "T-MS" =  list("tryptophan" = list(vars = c("tryptophan",
                                               "3-hydroxykynurenine",
                                               "3-hydroxyanthranilic acid",
                                               "kynurenic acid",
                                               "nicotinamide adenine ribonucleotide",
                                               "quinolinic acid",
                                               "nicotinic acid",
                                               "picolinic acid",
                                               "xanthurenic acid",
                                               "kynurenine",
                                               "indole-3-acetic acid",
                                               "dopamine",
                                               "5-hydroxyindole acetic acid",
                                               "neopterin",
                                               "beta-nicotinamide mononucleotide",
                                               "serotonin",
                                               "nicotinamide adenine dinucleotide"),
                                 sampleType = c("sample",
                                                "qc",
                                                "pqc",
                                                "blank",
                                                "standard",
                                                "ltr")),
                   "aminoAcids" = list(vars = c("1-methylhistidine",
                                                "3-methylhistidine",
                                                "Alanine",
                                                "alpha-aminobutyric acid",
                                                "Arginine",
                                                "Asparagine",
                                                "Aspartic acid",
                                                "beta-alanine",
                                                "beta-aminoisobutyric acid",
                                                "Citrulline",
                                                "Cystathionine",
                                                "Cystine",
                                                "gamma-aminobutyric acid",
                                                "Glutamic acid",
                                                "Glutamine",
                                                "Glycine",
                                                "Histidine",
                                                "Isoleucine",
                                                "Leucine",
                                                "Lysine",
                                                "Methionine",
                                                "Ornithine",
                                                "Phenylalanine",
                                                "Proline",
                                                "Sarcosine",
                                                "Serine",
                                                "Taurine",
                                                "Threonine",
                                                "Tyrosine",
                                                "Valine"),
                                       sampleType = c())

                   )
  )
  cat("replicates goes with # (we don't use _ or -)\n")
  return(melt)
}
