
#' help remembering
#'
#' @return a cheat list
#' @export
meltdown <- function() {
  melt <- list(
    "QUANT" = list(method = c("brxsm",
                              "brxlipo",
                              "spc",
                              "brxpacs",
                              "cytokines",
                              "antibodies",
                              "nmrQuant")),
    "NMR" = list(method = c("noesy",
                            "cpmg",
                            "jres",
                            "dire",
                            "diff",
                            "pgpe"),
                 sampleType = c("sample",
                                "pqc",
                                "standard",
                                "ltr",
                                "sltr"),
                 "smallMolecules" = list(vars = c("Alanine", "Creatine", "Creatinine", "Glutamic acid", "Glutamine", "Glycine", "Histidine", "Isoleucine","Leucine", "Lysine", "Methionine", "Phenylalanine", "Tyrosine", "Valine", "Acetic acid", "Citric acid", "Formic acid","Lactic acid", "3 Hydroxybutyric acid", "Acetoacetic acid", "Acetone", "Pyruvic acid", "Glucose"))),
    "MRMS" = list(method = c("DIPI",
                             "DINI"),
                 sampleType = c("sample",
                                "blank",
                                "qc",
                                "pqc",
                                "standard",
                                "ltr")),
    "T-MS" =  list(method = c("noesy",
                              "cpmg",
                              "jres",
                              "dire",
                              "diff",
                              "pgpe"),
                   sampleType = c("sample",
                                  "qc",
                                  "pqc",
                                  "blank",
                                  "standard",
                                  "ltr"),
                   "tryptophan" = list(vars = c("tryptophan",
                                               "3-hydroxykynurenine",
                                               "3-hydroxyanthranilic acid",
                                               "kynurenic acid",
                                               "nicotinamide adenine ribonucleotide",
                                               "quinolinic acid",
                                               "nicotinic acid",
                                               "picolinic acid",
                                               "xanthurenic acid",
                                               "kynurenine",
                                               "indole-3-acetic acid",
                                               "dopamine",
                                               "5-hydroxyindole acetic acid",
                                               "neopterin",
                                               "beta-nicotinamide mononucleotide",
                                               "serotonin",
                                               "nicotinamide adenine dinucleotide")),
                   "aminoAcids" = list(vars = c("1-methylhistidine",
                                                "3-methylhistidine",
                                                "Alanine",
                                                "alpha-aminobutyric acid",
                                                "Arginine",
                                                "Asparagine",
                                                "Aspartic acid",
                                                "beta-alanine",
                                                "beta-aminoisobutyric acid",
                                                "Citrulline",
                                                "Cystathionine",
                                                "Cystine",
                                                "gamma-aminobutyric acid",
                                                "Glutamic acid",
                                                "Glutamine",
                                                "Glycine",
                                                "Histidine",
                                                "Isoleucine",
                                                "Leucine",
                                                "Lysine",
                                                "Methionine",
                                                "Ornithine",
                                                "Phenylalanine",
                                                "Proline",
                                                "Sarcosine",
                                                "Serine",
                                                "Taurine",
                                                "Threonine",
                                                "Tyrosine",
                                                "Valine"),
                                       sampleType = c())
                   ),
    "boxType" = list("Num9x9",
                     "Let8x12",
                     "Num10x10")
  )
  message(cat(crayon::green("replicates goes with # (we don't use _ or -)\n")))
  return(melt)
}
